services:
  prom:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prom/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    depends_on:
      - promtail
    networks:
      - web-net2

  graf:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning
    networks:
      - web-net2

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/:/var/run/:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:rw
      - /dev/disk:/dev/disk:ro
    networks:
      - web-net2

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - --path.rootfs=/host
    restart: unless-stopped
    ports:
      - 9110:9100
    volumes:
     - /:/host:ro
    networks:
      - web-net2

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      -  3100:3100
    depends_on:
      - promtail
    networks:
      - web-net2

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command:
      - -config.file=/etc/promtail/promtail.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail.yml:/etc/promtail/promtail.yml:ro
      - /tmp:/tmp
    networks:
      - web-net2

networks:
  web-net2:
#    external: true
